---
services:

    mtt:
        image: ghcr.io/vigneshsubbaram/mtt:prod
        container_name: mtt
        ports:
            - 8000:8000
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            - MTT_CONTROL_SERVER_PORT=8000
            - OPERATION_MODE=on_premise
            - IS_OMNILAB_BASED=true
        restart: unless-stopped

    nginx:
        image: nginx:alpine
        ports:
            - 8001:80
        configs:
            - source: nginx_config
              target: /etc/nginx/nginx.conf
            - source: htpasswd
              target: /etc/nginx/.htpasswd
        depends_on:
            - mtt
        restart: unless-stopped

    cuttlefish:
        build:
            context: >-
                https://github.com/vigneshsubbaram/fishtank.git#master:components/cuttlefish
            dockerfile: Dockerfile
            args:
                BUILD_ID: '15067704'
                ARCH: x86_64
                BRANCH: aosp-android13-gsi
                TARGET_x86_64: aosp_cf_x86_64_only_phone-userdebug
                TARGET_arm64: aosp_cf_arm64_only_phone-userdebug
        image: cuttlefish:latest
        container_name: cuttlefish
        privileged: true
        devices:
            - /dev/kvm
            - /dev/net/tun
            - /dev/vhost-net
            - /dev/vhost-vsock
            - /dev/dri
        cap_add:
            - NET_ADMIN
            - NET_RAW
            - SYS_ADMIN
            - SYS_PTRACE
            - MKNOD
        security_opt:
            - seccomp=unconfined
        tmpfs:
            - /tmp
        ports:
            - 5900:5900
            - 6520:6520
        deploy:
            resources:
                limits:
                    memory: 10g
        memswap_limit: 10g
        stdin_open: true
        tty: true

    ota-server:
        container_name: ota
        image: ghcr.io/vigneshsubbaram/ota-server:container_utils_1.1.1
        environment:
            LEGACY: no  # yamllint disable-line rule:truthy
        privileged: true
        hostname: ota

    orchestrator:
        container_name: orchestrator
        image: ghcr.io/vigneshsubbaram/raikou-net:alpine3.18-dind-ovs_2.17
        volumes:
            - /lib/modules:/lib/modules
            - /var/run/docker.sock:/var/run/docker.sock
            - $NW_CONFIG:/root/config.json
        privileged: true
        pid: host
        network_mode: host
        hostname: orchestrator
        depends_on:
            - cuttlefish
            - ota-server
            - mtt

configs:
    nginx_config:
        content: |
            events { worker_connections 1024; }
            http {
                server {
                    listen 80;
                    location / {
                        auth_basic "ATS";
                        auth_basic_user_file /etc/nginx/.htpasswd;
                        proxy_pass http://mtt:8000;
                    }
                }
            }

    htpasswd:
        content: |
            admin:$2y$05$7eaUZOK1Q7SuT9tv67PwvulFo7/ysDHS8bKM6G4rENSJZdEMlMa42
